const mediaProjection = `{
  _id,
  _type,
  title,
  alt,
  "url": asset.asset->url,
  "dimensions": asset.asset->metadata.dimensions,
  "crop": asset.crop,
  "hotspot": asset.hotspot
}`;

const buttonActionProjection = `{actionType, section, externalUrl}`;
const publicLinkProjection = `{url, isVisible}`;

export const SANITY_SITE_CONTENT_QUERY = `{
  "siteSettings": *[_type == "siteSettings" && _id == "siteSettings"][0]{
    siteName,
    siteUrl,
    primaryContact,
    timezone,
    copyright,
    socialLinks[]{_key, network, label, url, isVisible},
    "logoFull": logoFull->${mediaProjection},
    "logoMark": logoMark->${mediaProjection},
    "favicon": favicon->${mediaProjection}
  },
  "linksSettings": *[_type == "linksSettings" && _id == "linksSettings"][0]{
    primaryTelegram${publicLinkProjection},
    telegramBot${publicLinkProjection},
    telegramChannel${publicLinkProjection},
    vkontakte${publicLinkProjection},
    youtube${publicLinkProjection},
    dzen${publicLinkProjection},
    rutube${publicLinkProjection},
    instagram${publicLinkProjection},
    whatsapp${publicLinkProjection},
    portfolio${publicLinkProjection}
  },
  "hero": *[_type == "hero" && _id == "hero"][0]{
    eyebrow,
    titleMain,
    titleAccent,
    subtitle,
    description,
    primaryCtaLabel,
    primaryCtaAction,
    primaryButtonAction${buttonActionProjection},
    ctaNote,
    founderLabel,
    expertName,
    expertRole,
    "image": image->${mediaProjection}
  },
  "navigation": *[_type == "navigation" && _id == "navigation"][0]{
    items[]{_key, label, href, destination${buttonActionProjection}, order, isVisible},
    portfolioLabel,
    portfolioUrl,
    consultationLabel,
    consultationAction,
    consultationButtonAction${buttonActionProjection}
  },
  "manifesto": *[_type == "manifesto" && _id == "manifesto"][0]{
    isVisible,
    eyebrow,
    heading,
    mainText,
    additionalText,
    ctaLabel,
    ctaTarget,
    buttonAction${buttonActionProjection},
    "image": image->${mediaProjection}
  },
  "competencies": *[_type == "competencies" && _id == "competencies"][0]{
    eyebrow,
    title,
    description,
    cards[]{_key, internalKey, title, description, additionalLabels, icon, order, isVisible}
  },
  "expert": *[_type == "expert" && _id == "expert"][0]{
    eyebrow,
    name,
    role,
    founderStatus,
    description,
    credentialsTitle,
    facts,
    audienceTitle,
    audienceDescription,
    ctaLabel,
    telegramUrl,
    buttonAction${buttonActionProjection},
    "portrait": portrait->${mediaProjection},
    "workPhoto": workPhoto->${mediaProjection}
  },
  "experience": *[_type == "experience" && _id == "experience"][0]{
    factsTitle,
    facts,
    cards[]{_key, internalKey, label, text, icon, order, isVisible}
  },
  "transformationSteps": *[_type == "transformationSteps" && _id == "transformationSteps"][0]{
    eyebrow,
    title,
    description,
    itemLabel,
    items[]{_key, internalKey, number, title, description, order, isVisible}
  },
  "speechLab": *[_type == "speechLab" && _id == "speechLab"][0]{
    eyebrow,
    title,
    description,
    situationLabel,
    completedLabel,
    progressAriaLabel,
    backLabel,
    resultEyebrow,
    recommendationLabel,
    questions[]{_key, internalKey, shortTitle, prompt, order, options[]{_key, text, weight}},
    results[]{_key, internalKey, title, description, recommendation, minScore, maxScore, order},
    ctaTitle,
    ctaDescription,
    ctaLabel,
    buttonAction${buttonActionProjection},
    resetLabel,
    "image": image->${mediaProjection}
  },
  "leadFormContent": *[_type == "leadFormContent" && _id == "leadFormContent"][0]{
    eyebrow,
    title,
    description,
    nameLabel,
    namePlaceholder,
    nameHint,
    nameMin,
    nameMax,
    contactLabel,
    contactPlaceholder,
    contactHint,
    contactMin,
    contactMax,
    messageLabel,
    messagePlaceholder,
    messageHint,
    messageMin,
    messageMax,
    submitLabel,
    submittingLabel,
    telegramLabel,
    fallbackButtonAction${buttonActionProjection},
    idleMessage,
    successMessage,
    errorMessage,
    unavailableMessage,
    validationMessage,
    nameRequiredMessage,
    nameLengthMessage,
    contactRequiredMessage,
    contactLengthMessage,
    messageRequiredMessage,
    messageLengthMessage,
    consentRequiredMessage,
    legalPrefix,
    legalLinkLabel,
    legalSuffix,
    privacyPolicyUrl,
    publicTelegramUrl
  },
  "footer": *[_type == "footer" && _id == "footer"][0]{
    brandName,
    description,
    navigationTitle,
    navigationLinks[]{_key, internalKey, label, href, action${buttonActionProjection}, order, isVisible},
    socialTitle,
    socialLinks[]{_key, network, label, url, isVisible},
    copyright,
    statusText
  },
  "legal": *[_type == "legal" && _id == "legal"][0]{
    entityType,
    ownerFullName,
    inn,
    ogrnip,
    privacyPolicyUrl,
    consentPrefix,
    consentLinkLabel,
    consentSuffix,
    publicOfferUrl
  },
  "seo": *[_type == "seo" && _id == "seo"][0]{
    siteName,
    author,
    locale,
    title,
    description,
    canonicalUrl,
    allowIndexing,
    ogTitle,
    ogDescription,
    twitterCard,
    socialLinks[]{_key, network, label, url, isVisible},
    "ogImage": ogImage->${mediaProjection}
  }
}`;
