import {defineField, defineType} from 'sanity'
import {editorialNoticeField} from '../editorialNotice.jsx'
import {validateReferencedMediaAlt, validateSafePublicUrl} from '../validation.js'

export const manifesto = defineType({
  name: 'manifesto',
  title: 'Философия',
  type: 'document',
  description: 'Тексты, фотография и кнопка раздела «Почему речь имеет значение».',
  initialValue: {isVisible: true, ctaTarget: 'scrollToForm'},
  groups: [
    {name: 'content', title: 'Тексты', default: true},
    {name: 'media', title: 'Фотография'},
    {name: 'button', title: 'Кнопка'},
    {name: 'visibility', title: 'Показ раздела'},
  ],
  fields: [
    editorialNoticeField,
    defineField({
      name: 'isVisible',
      title: 'Показывать раздел',
      description: 'Отключите только если раздел нужно временно скрыть целиком.',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    }),
    defineField({
      name: 'eyebrow',
      title: 'Верхняя короткая подпись',
      description: 'Небольшой текст над содержанием раздела.',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required().max(100).warning('Проверьте длинную подпись на мобильном экране.'),
    }),
    defineField({
      name: 'heading',
      title: 'Главный акцентный текст',
      description: 'Текст, который визуально работает как заголовок раздела.',
      type: 'text',
      rows: 4,
      group: 'content',
      validation: (Rule) => [Rule.required().min(20).error('Заполните главный текст.'), Rule.max(600).warning('Текст длиннее 600 символов стоит проверить на мобильном экране.')],
    }),
    defineField({
      name: 'mainText',
      title: 'Основной поясняющий текст',
      type: 'text',
      rows: 4,
      group: 'content',
      validation: (Rule) => [Rule.required().min(20).error('Заполните поясняющий текст.'), Rule.max(600).warning('Текст длиннее 600 символов может быть тяжело читать.')],
    }),
    defineField({
      name: 'additionalText',
      title: 'Дополнительный текст',
      description: 'Необязательный короткий абзац. Оставьте пустым, если он не нужен.',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (Rule) => Rule.max(400).warning('Дополнительный текст длиннее 400 символов стоит сократить.'),
    }),
    defineField({
      name: 'image',
      title: 'Фото раздела «Философия»',
      description: 'Выберите фотографию из раздела «Изображения».',
      type: 'reference',
      group: 'media',
      to: [{type: 'media'}],
      options: {filter: 'usage in ["section", "portrait"]'},
      validation: (Rule) => [Rule.required().error('Выберите фотографию.'), Rule.custom(validateReferencedMediaAlt)],
    }),
    defineField({
      name: 'ctaLabel',
      title: 'Текст на кнопке',
      type: 'string',
      group: 'button',
      validation: (Rule) => [Rule.required().min(2).error('Укажите текст кнопки.'), Rule.max(60).warning('Проверьте длинный текст кнопки на 320 px.')],
    }),
    defineField({
      name: 'ctaTarget',
      title: 'Прежняя ссылка кнопки',
      type: 'string',
      group: 'button',
      hidden: true,
      readOnly: true,
      validation: (Rule) => Rule.custom((value) => !value || validateSafePublicUrl(value)),
    }),
    defineField({
      name: 'buttonAction',
      title: 'Что должна делать кнопка?',
      type: 'buttonAction',
      group: 'button',
      validation: (Rule) => Rule.required().error('Выберите действие кнопки.'),
    }),
  ],
  preview: {
    select: {subtitle: 'eyebrow'},
    prepare: ({subtitle}) => ({title: 'Философия', subtitle: subtitle || 'Текст раздела'}),
  },
})
